### ISSUE TITLE
Navbar Responsiveness

### ISSUE THREAD

**Issue by lucasmarcelli** [lucasmarcelli/mood-tracker#17]
The navbar isn't very responsive now I'm adding more things to it. I'm pretty new to bootstrap, could you teach me how to make it more responsive or point me to a tutorial @OSP123 ? 🍡

**Comment by OSP123** [comment]
Hmm, I might have to just go through documentation. Honestly, I keep forgetting all of the things that Bootstrap has. If you live in LA and have a county of LA library card, you can use the lynda.com tutorial for free. Otherwise, you might have to just parse through the Bootstrap docs for the nav elements :/ 

```
On Friday, April 8, 2016 3:01 PM, Lucas Marcelli <notifications@github.com> wrote:
```

 The navbar isn't very responsive now I'm adding more things to it. I'm pretty new to bootstrap, could you teach me how to make it more responsive or point me to a tutorial @OSP123 ? 🍡  —

**Comment by OSP123** [comment]
Hey Lucas, I'm going to start working on this right now.

**Comment by OSP123** [comment]
OK, I added responsive navigation using Boostrap. Let me know what you think. It's under the branch "style_changes"

**Comment by OSP123** [comment]
Also, I just used http://www.w3schools.com/bootstrap/bootstrap_navbar.asp for the tutorial. I know it's not the official source and sometimes has issues, but w3schools is pretty good for basic stuff.
